server:
  port: 8080
spring:
  application:
    name: bento-sushi-web
  datasource:
    driver-class: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
