version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bento-sushi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
